name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: mirror set
        run: npm config set registry http://mirrors.cloud.tencent.com/npm/


      - name: i
        # install in your project
        run: npm install -D vuepress@next
        
        
      #- name: npm i
        #run: npm i
      - name: Build
        run: npx vuepress build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: .vuepress/dist
          #这个 peaceiris action 默认会将构建的静态文件部署到 gh-pages 分支上，这里不设置也行
          publish_branch: gh-pages
